name: qn-marketplace-cli tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          PGPASSWORD: password
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          path: webapp

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"

      - name: Create .env file
        run: |
          cd webapp && cat > .env <<EOL
          DB_URL=postgres://username:password@localhost:5432/test
          JWT_SECRET=jwt-secret
          HOST=localhost
          POST=3009
          AUTH_USERNAME=username
          AUTH_PASSWORD=password
          EOL

      - name: Install foreman
        run: gem install foreman

      - name: Install dependencies
        run: cd webapp && bundle install

      - name: Migrate database
        run: cd webapp && bin/rails db:migrate

      - name: Start the web app in the background
        run: |
          cd webapp && bin/dev &
          sleep 3  # Give the web app some time to start

      - name: Check out source code for qn-marketplace-cli
        uses: actions/checkout@v2
        with:
          repository: quiknode-labs/qn-marketplace-cli
          ref: main
          path: cli

      - name: Build qn-marketplace-cli
        run: cd cli && go build

      - name: Conduct a healthcheck
        run: ./cli/qn-marketplace-cli healthcheck --url http://localhost:3009/healthcheck

      - name: Conduct a PUDD test
        run: ./cli/qn-marketplace-cli pudd --base-url http://localhost:3009 --basic-auth dXNlcm5hbWU6cGFzc3dvcmQ=

      - name: Test RPC
        run: ./cli/qn-marketplace-cli rpc --url http://localhost:3009/provision --rpc-url http://localhost:3009/rpc --rpc-method bb_getAddress --rpc-params "[\"abc\"]" --basic-auth dXNlcm5hbWU6cGFzc3dvcmQ=

      - name: Test SSO
        run: ./cli/qn-marketplace-cli sso --url http://localhost:3009/provision  --basic-auth dXNlcm5hbWU6cGFzc3dvcmQ= --jwt-secret jwt-secret --email jon@example.com --name jon --org QuickNode